import { Cormorant_Garamond, Poppins } from "next/font/google";
import IntroLoader from "../components/IntroLoader";
import Navbar from "../components/Navbar";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
  variable: "--font-poppins",
});

const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  display: "swap",
  variable: "--font-cormorant",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable} ${cormorant.variable}`}>
      <body className={poppins.className}>
        <div className="site-shell">
          <IntroLoader />
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
